# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 819fd3d14a060e7b2d4503e62dc527f784a9670d17296c0e21f206f51266476ddcc0d97e09e144b904efa709d62c560a134139666097b227e6ded0a4a5a70fe4

test:
  secret_key_base: 4e83c74e140c586174611f7b2012e4dfa182e47a27d570555a12db7d0ee0ded8bd5d16b0375c315fcd64cc6016ef9eb4f0d8c78daeace87fbe9bc9b2b592c159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
